version: '3.8'

services:
  app:
    build:
      context: server/
      dockerfile: Dockerfile
    depends_on:
      - webserver

  webserver:
    image: nginx:mainline
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
